module RegistrationsHelper
  def options_for_college
    [
      ["All Soul's", "all-souls"],
      ["Balliol", "balliol"],
      ["Blackfriars", "bfriars"],
      ["Brasenose", "bnc"],
      ["Campion Hall", "campion"],
      ["Christ Church", "chch"],
      ["Corpus Christi", "ccc"],
      ["Exeter", "exeter"],
      ["Green Templeton", "gtc"],
      ["Harris Manchester", "hmc"],
      ["Hertford", "hertford"],
      ["Jesus", "jesus"],
      ["Keble", "keble"],
      ["Kellogg", "kellogg"],
      ["Lady Margaret Hall", "lmh"],
      ["Linacre", "linacre"],
      ["Lincoln", "lincoln"],
      ["Magdalen", "magd"],
      ["Mansfield", "mansfield"],
      ["Merton", "merton"],
      ["New", "new"],
      ["Nuffield", "nuffield"],
      ["Oriel", "oriel"],
      ["Pembroke", "pmb"],
      ["Queen's", "queens"],
      ["Regent's Park", "rpc"],
      ["St Anne's", "st-annes"],
      ["St Benet's Hall", "st-benets"],
      ["St Catherine's", "stcatz"],
      ["St Cross", "stx"],
      ["St Edmund Hall", "seh"],
      ["St Hilda's", "st-hildas"],
      ["St Hugh's", "st-hughs"],
      ["St John's", "sjc"],
      ["St Peter's", "spc"],
      ["St Stephen's House", "ssho"],
      ["Somerville", "somerville"],
      ["Trinity", "trinity"],
      ["University", "univ"],
      ["Wadham", "wadham"],
      ["Wolfson", "wolfson"],
      ["Worcester", "worc"],
      ["Wycliffe Hall", "wycliffe"],
      ["St Hugh's Alumni", "st-hughs-alumni"],
      ["Oxford (other)", "oxford-other"],
    ]
  end
end
